@echo off
echo 🚀 Starting Sanity Studio...
echo.

echo 🔍 Trying port 3333...
netstat -an | find ":3333" >nul
if %errorlevel% == 0 (
    echo ❌ Port 3333 is busy, trying 3334...
    netstat -an | find ":3334" >nul
    if %errorlevel% == 0 (
        echo ❌ Port 3334 is busy, trying 3335...
        echo ✅ Starting on port 3335...
        npm run dev-3335
    ) else (
        echo ✅ Starting on port 3334...
        npm run dev-3334
    )
) else (
    echo ✅ Starting on port 3333...
    npm run dev
)